// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjs9E0tGyw7nfro5IrC5qjLnPm0IcFuE',
    appId: '1:602301372169:web:2f8ef946cbcdf32dcd25d8',
    messagingSenderId: '602301372169',
    projectId: 'campusconnect-50c2c',
    authDomain: 'campusconnect-50c2c.firebaseapp.com',
    storageBucket: 'campusconnect-50c2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8YRosPn1s8Rqy6eW5liZtEBS1Wkp2to',
    appId: '1:602301372169:android:0059fc7dd8eeae48cd25d8',
    messagingSenderId: '602301372169',
    projectId: 'campusconnect-50c2c',
    storageBucket: 'campusconnect-50c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Un0q87AlI4WxuY8w1qTbE8rdIix1llg',
    appId: '1:602301372169:ios:b5e1adb21e1ea051cd25d8',
    messagingSenderId: '602301372169',
    projectId: 'campusconnect-50c2c',
    storageBucket: 'campusconnect-50c2c.firebasestorage.app',
    iosBundleId: 'com.comsats.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Un0q87AlI4WxuY8w1qTbE8rdIix1llg',
    appId: '1:602301372169:ios:b5e1adb21e1ea051cd25d8',
    messagingSenderId: '602301372169',
    projectId: 'campusconnect-50c2c',
    storageBucket: 'campusconnect-50c2c.firebasestorage.app',
    iosBundleId: 'com.comsats.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJjs9E0tGyw7nfro5IrC5qjLnPm0IcFuE',
    appId: '1:602301372169:web:ece747abb523ebd9cd25d8',
    messagingSenderId: '602301372169',
    projectId: 'campusconnect-50c2c',
    authDomain: 'campusconnect-50c2c.firebaseapp.com',
    storageBucket: 'campusconnect-50c2c.firebasestorage.app',
  );
}
